#!/bin/bash

usage() {
  echo "Usage: $0 HEXCOLOR"
  echo "    or $0 RED GREEN BLUE"
  exit 1
}

hex2ansi() {
  case "${#1}" in
    6) echo "\033[38;2;$(printf "%d;%d;%d" ${1:0:2} ${1:2:2} ${1:4:2})m";;
    3)
      rhex="${1:0:1}${1:0:1}"
      ghex="${1:1:1}${1:1:1}"
      bhex="${1:2:1}${1:2:1}"
      echo "\033[38;2;$(printf "%d;%d;%d" $rhex $ghex $bhex)m"
      ;;
    *) usage;;
  esac
}

checkValidRGB() {
  [ $1 -ge 0 ] && [ $1 -le 255 ]
}

rgb2ansi() {
  (checkValidRGB $1 && checkValidRGB $2 && checkValidRGB $3) || usage
  echo "\033[38;2;$1;$2;$3m"
}

main() {
  case "$#" in
    1) hex2ansi $@;;
    3) rgb2ansi $@;;
    *) usage;;
  esac
}

main $@
