#!/bin/bash
# Tmux layouts

if [[ -z "${TMUX}" ]]; then
  echo "This script requires tmux to be running."
  exit 1
fi

# For UNSW CSE subjects
cs() {
  tmux split-window -h
  tmux select-pane -L
  tmux split-window -v
  tmux select-pan -U
  echo "Using layout 'cs'"
}

layouts=( "cs" )

if [[ "${layouts[@]}" =~ "${1}" ]]; then
  "${1}" "$@"
else
  echo "usage: ${0} LAYOUT"
  echo "layouts:"
  for lyt in "${layouts[@]}"; do
    echo "- ${lyt}"
  done
fi

