#!/bin/bash
# Tmux layouts

if [[ -z "${TMUX}" ]]; then
  echo "This script requires tmux to be running."
  exit 1
fi

# For UNSW CSE subjects
cs() {
  tmux split-window -h
  tmux select-pane -L
  tmux split-window -v
  tmux select-pan -U
}

grid4() {
  tmux split-window -h
  tmux split-window -v
  tmux select-pane -L
  tmux split-window -v
  tmux select-pan -U
}

layouts=( "cs" "grid4" )

for layout in "${layouts}"; do
  if [[ "${layout}" == "${1}" ]]; then
    "${1}" "$@"
    echo "Using layout ${1}"
    exit
  fi
done

echo "usage: ${0} LAYOUT"
echo "layouts:"
for lyt in "${layouts[@]}"; do
  echo "- ${lyt}"
done

