#!/usr/bin/env bash

if [[ -v $DEBUG ]]; then
  set -x
fi

set -euo pipefail

echo_usage() {
  echo "Usage: pr [feature|hotfix|draft|ready|view|help]"
}

if ! command -v gh &>/dev/null; then
  echo "Install github cli to continue"
  echo "https://cli.github.com/"
  exit 1
fi;

repo=$(git remote -v | grep origin | grep fetch | cut -d':' -f2 | cut -d'.' -f1)

pr_type="${1:-feature}"

if [[ "$pr_type" = "help" ]]; then
  echo_usage
  exit 0
fi

if [[ $pr_type = "ready" ]]; then
  gh pr ready
  exit 0
fi

if [[ $pr_type = "view" ]]; then
  gh pr view -w
  exit 0
fi


if [[ ! "$pr_type" =~ ^(feature|hotfix|draft)$ ]]; then
  echo_usage
  exit 1
fi

declare -A default_base_branch_map=(
  ["RelevanceAI/relevance-api-node"]="development"
)
base_branch="main"
if [[ -v default_base_branch_map[$repo] ]]; then
  base_branch="${default_base_branch_map[$repo]}"
fi

args=""
if [[ $pr_type = "draft" ]]; then
  args="--draft"
fi


declare -A extra_args_map=(
  ["RelevanceAI/relevance-app"]=""
  ["RelevanceAI/relevance-api-node"]=""
  ["RelevanceAI/relevance-global-api"]=""
)

gh pr create $args

