#!/usr/bin/env bash

path="$1"

if [ "$path" = "." ]; then
  cwd=$(pwd)

  # if pwd ends with /repos/*, open the repo (but not /repos/*/*)
  if [[ "$cwd" == */repos/* && "$cwd" != */repos/*/* ]]; then
    echo "$cwd"
  else
    # find closest parent git repo
    git_root=$(git rev-parse --show-toplevel 2>/dev/null || echo '.')
    echo "$git_root"
  fi
else
  echo "$path"
fi