#!/bin/sh
# Attach to and switch between tmux sessions

if [ "${1}" = "ls" ]; then
  tmux list-sessions
  exit
fi

if [ -n "${1}" ]; then
  session="${1}"

  if [ -z "${TMUX}" ]; then
    # Join existing session, or create a new one
    tmux a -t "$session" 2>/dev/null || tmux new -s "$session"
  else
    # Create a new detached session
    tmux new -d -s "$session" 2>/dev/null
    # Switch to the session
    tmux switch-client -t "$session"
  fi
else
  if [ -z "${TMUX}" ]; then
    # Attach to the most recent session, or create a new session
    tmux a || tmux
  fi
fi

