#!/bin/sh

# Default editor
editor="$EDITOR"

# Parse command-line options
while getopts "c" opt; do
  case ${opt} in
    c)
      editor="code"  # Set editor to 'code' if -c flag is used
      ;;
    \?)
      echo "Usage: ${0##*/} [-c] SCRIPT | ls"
      exit 1
      ;;
  esac
done

# Shift arguments to get to the script or 'ls'
shift $((OPTIND - 1))

[ -z "${1}" ] && {
  echo "Usage: ${0##*/} SCRIPT | ls"
  exit 1
}

scriptDir="${HOME}/repos/scripts/"

if [ "${1}" = "ls" ]; then
  # find $scriptDir -maxdepth 1 -type f
  ls -p "$scriptDir"
  exit
fi

file="${scriptDir}${1}"

if [ ! -f "${file}" ]; then
  touch "${file}"
  chmod +x "${file}"
fi

$editor "${file}"

if [ ! -s "${file}" ]; then
  rm "${file}" >/dev/null
fi

